version: 2.1

parameters:
  gio_action:
    type: enum
    enum: [this_one, another_one]
    default: this_one
  have_a_great_we:
    type: string
    default: "Awesome have a great week end everyone ! :D"
    description: "A hapy we message to the world :) "
orbs:
  slack: circleci/slack@4.2.1
  gravitee: gravitee-io/gravitee@1.0
  # gravitee: gravitee-io/gravitee@dev:1.0.41
  secrethub: secrethub/cli@1.1.0
jobs:
  myawesome_job:
    docker:
      - image: 'cimg/node:16.3.0'
      # - image: 'cimg/base:stable'
    environment:
      GUESS_WHOIAM: 'I am Jean-Baptiste Lasselle!!'
      SOME_MESSAGE: << pipeline.parameters.have_a_great_we >>
    steps:
      - checkout
      - run:
          name: "System setup: Install [bash] [curl] [jq] [apt-transport-https] [ca-certificates]"
          command: |
                    echo "Install [bash] [curl] [jq] [apt-transport-https] [ca-certificates]"
                    sudo apt-get update -y && sudo apt-get install -y bash curl jq apt-transport-https ca-certificates ip-utils
      - run:
          name: "Checking Pipeline environment variables"
          command: |
                    echo "# ---------------------------------------------------------------------- #"
                    echo "    Checking Pipeline environment variables"
                    echo "# ---------------------------------------------------------------------- #"
                    echo "# ----      GUESS_WHOIAM=[${GUESS_WHOIAM}]"
                    echo "# ----      SOME_MESSAGE=[${SOME_MESSAGE}]"
                    echo "# ---------------------------------------------------------------------- #"
      - attach_workspace:
          at: /tmp
      - setup_remote_docker
      - run:
          name: "Here I will run [https://gettaurus.org/] laod tests against the Cloudflare Load Balancer"
          command: |
                    echo "Here I will run gattaurrus.org laod tests against the Cloudflare Load Balancer"
                    ping -c 4 gravit33-docs.herokuapp.com || true
                    ping -c 4 example.com || true

workflows:
  version: 2.1
  # -- typically this workflow is executed on pull requests events for Community Edition Gravitee Repositories
  myworkflow:
    when:
      and:
        - equal: [ this_one, << pipeline.parameters.gio_action >> ]
    jobs:
      - myawesome_job:
          name: thats_myawesome_job
